### ISSUE TITLE
Erro Package 'json'

### ISSUE THREAD

**Issue by ScrimForever** [graniet/operative-framework#1]
ollecting json (from -r requirements.txt (line 7))
  Using cached json-99.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s1ezJh/json/setup.py", line 2, in <module>
        raise RuntimeError("Package 'json' must not be downloaded from pypi")
    RuntimeError: Package 'json' must not be downloaded from pypi
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s1ezJh/json/

Can you help me ?

**Comment by graniet** [comment]
Hello,

Thanks for use Operative Framework

What is your OS?

**Comment by ScrimForever** [comment]
Kali Linux 2016-2

**Comment by qwartz2** [comment]
@ScrimForever I had the same error in Debian, solution:` pip install simplejson`
