### ISSUE TITLE
Issue with incorrect indentation compatibility on OS X 

### ISSUE THREAD

**Issue by jackleonard** [graniet/operative-framework#12]
Mixture of Tabs & Spaces not supported by OS X Python Interpreter

**Comment by Ph03n1x-Crus4d3** [comment]
Mixture of Tabs & Spaces not supported by OS X Python Interpreter
![screen shot 2018-03-05 at 4 52 26 pm](https://user-images.githubusercontent.com/26177794/37001770-9a18e68a-2095-11e8-8ad3-09f8528e00b9.png)

**Comment by graniet** [comment]
Hello,

Thanks for using Operative Framework.

Please launch operative framework without opening on IDE, or configure your IDE with correct tab space example here: 

"_Set your editor to use 4 spaces for indentation.
Make a search and replace to replace all tabs with 4 spaces.
Make sure your editor is set to display tabs as 8 spaces._"

**Source:** https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation

**Comment by AiyionPrime** [comment]
[The answer you're quoting](https://stackoverflow.com/a/5685816/3458484) is following up with:

> Note: The reason for 8 spaces for tabs is so that you immediately notice when tabs have been inserted unintentionally - such as when copying and pasting from example code that uses tabs instead of spaces.

So I think it's supporting @jackleonard s point here. Right?
