### ISSUE TITLE
Export: can't write

### ISSUE THREAD

**Issue by OSINT-d** [graniet/operative-framework#16]
Hi everyone!
I am new to operative framework and I can't export the results of my research. When I give the command "export" and then give a name to the destination file, the software answers me with:

ERROR: Can't write element.
...
...
File writed : export/file

This is the first time I use operative so I changed nothing on its settings but simply tried to search for information I needed.

What should I do? thank you!

**Comment by BaRRaKudaRain** [comment]
Have you any logs of program's work, or some other Info?

--
-----------------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by graniet** [comment]
Hello @OSINT-d @BaRRaKudaRain ,

A new version of operative framework written in Golang will be released next Tuesday.
With multiple new features example: Twitter osint, whatsapp osint, report PDF, phone buster... etc.

**Comment by BaRRaKudaRain** [comment]
Thanks for information!

-----Original Message-----
