### ISSUE TITLE
Help in instalation

### ISSUE THREAD

**Issue by meetgyn** [graniet/operative-framework#17]
**I can not install in Debian 9**
root@kron:/opt/ferramentas/scans/operative-framework# go get  github.com/graniet/operative-framework
# github.com/jedib0t/go-pretty/text
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/align.go:97: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/ansi.go:39: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/color.go:128: undefined: sync.Map
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/string.go:31: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:101: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:130: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:172: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:185: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:191: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/wrap.go:220: undefined: strings.Builder
/root/opt/ferramentas/scans/src/github.com/jedib0t/go-pretty/text/string.go:31: too many errors
# github.com/jinzhu/gorm
/root/opt/ferramentas/scans/src/github.com/jinzhu/gorm/main.go:27: undefined: sync.Map
# github.com/segmentio/ksuid
/root/opt/ferramentas/scans/src/github.com/segmentio/ksuid/rand.go:47: undefined: "math/rand".Source64
# syreclabs.com/go/faker
/root/opt/ferramentas/scans/src/syreclabs.com/go/faker/faker.go:288: undefined: rand.Source64
# github.com/jung-kurt/gofpdf
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/fpdf.go:3808: undefined: sort.SliceStable
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/fpdf.go:3857: undefined: sort.SliceStable
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/fpdf.go:4168: undefined: sort.SliceStable
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/fpdf.go:4248: undefined: sort.SliceStable
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/fpdf.go:4288: undefined: sort.SliceStable
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/utf8fontfile.go:854: undefined: math.Round
/root/opt/ferramentas/scans/src/github.com/jung-kurt/gofpdf/utf8fontfile.go:872: undefined: math.Round
root@kron:/opt/ferramentas/scans/operative-framework#

**Comment by graniet** [comment]
Hello,

Thanks for your message.

You can try with build in releases section on Github?

Thanks.

**Comment by meetgyn** [comment]
Hi, how are you?
Many thanks for your feedback.

**Comment by tdelozie** [comment]
I understand this section is closed but, I can't seem to locate the installation guide for the latest version of this repository. The requirments.txt file is no longer applicable it seems. Do you have a link to an installation guide?
