### ISSUE TITLE
cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by ExtReMLapin** [graniet/operative-framework#18]
Hello,

When trying to run the whatsapp extractor module I run into this error : 

```
[OPF v1.00 (reborn)]: whatsapp_extractor run
error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

```

**Comment by graniet** [comment]
Hello,

Thanks for using Operative Framework.
Which binary do you use? I thinks it's a release compiling problem.

Regards.

**Comment by ExtReMLapin** [comment]
Hello and thanks for the fast answer.
I'm using the Linux amd64 binary on Ubuntu 18.04.2 LTS

**Comment by graniet** [comment]
I have updated a new binary to release section.

You can try now?

Thanks.

**Comment by ExtReMLapin** [comment]
Yep it's fixed, thanks for the really quick fix !
