### ISSUE TITLE
some examples in documentation

### ISSUE THREAD

**Issue by lucmski** [graniet/operative-framework#19]
Hi,

Hope you are all well !

Would be awesome to have some examples or tutorials in the doc.

Have a great day !

Cheers,

**Comment by graniet** [comment]
Hello !

Thanks for your message.

What tutorial can be help you :) ?

Regards.

**Comment by lucmski** [comment]
lol, I was talking about you just now...

Like this one:
https://www.zataz.com/osint-des-numeros-de-politiques-francaises-interceptes-via-whatsapp/

**Comment by lucmski** [comment]
Do you have a telegram account ? (ps. je suis francais)

**Comment by graniet** [comment]
Voici mon mail: graniet75 at gmail com :)
