### ISSUE TITLE
No requirements

### ISSUE THREAD

**Issue by Bobpick** [graniet/operative-framework#20]
When attempting to follow the directions here:
https://null-byte.wonderhowto.com/how-to/recon-research-person-organization-using-operative-framework-0176323/

The command to install the requirements fails because there is no requirements.txt.

Any suggestions?

**Comment by graniet** [comment]
Hello !

Thanks for your message,

This article is based on **old operative framework version**.

Now OPF it is written in Go, you can **download last release and run it without requirement** here:

https://github.com/graniet/operative-framework/releases

Thanks.
