### ISSUE TITLE
Instagram.info Error!!

### ISSUE THREAD

**Issue by N4n00K-Nikto** [graniet/operative-framework#29]
I'm trying to use the instagram.info Module, i add the target as instagram, run the command instagram.info target <target id>. Then instagram.info run.
shows me the next error:
fail: Invalid Parameters (missing_parameters)
i'm missing something???

**Comment by graniet** [comment]
Hello @N4n00K-Nikto,

Thanks for using operative framework,
You need to add a target ID with **instagram.info target** like this: **instagram.info target T_1....**

Example here with github instagram:

`[OPF v1.10 (voyager)]: target add instagram github`
`> target 'github' as successfully added with id 'T_1WwGVCk9G4vZOgKrSg3zr3rRnW1'`
`[OPF v1.10 (voyager)]: instagram.info target T_1WwGVCk9G4vZOgKrSg3zr3rRnW1`
`[OPF v1.10 (voyager)]: instagram.info run`

**Comment by graniet** [comment]
Same  if you want see instagram following:

`instagram.following target T_1WwGVCk9G4vZOgKrSg3zr3rRnW1`
`instagram.following run`

You can view target results with:

`target view results T_1WwGVCk9G4vZOgKrSg3zr3rRnW1 instagram.following`

**Comment by graniet** [comment]
If you want see related targets you can use:

`target links T_1WwGVCk9G4vZOgKrSg3zr3rRnW1`

Exemple if you follow this steps:

- target add instagram github
- instagram.following target T_1WwGVCk9G4vZOgKrSg3zr3rRnW1
- instagram.following run
- target add instagram airbnbdesignteam

Execute command: `target links T_1WwGVCk9G4vZOgKrSg3zr3rRnW1`
We see relation beetwen: **github** & **airbnbdesignteam**

**Comment by N4n00K-Nikto** [comment]
Thanks I’ll try it and let you know
