### ISSUE TITLE
No requirements.txt file

### ISSUE THREAD

**Issue by zoben10** [graniet/operative-framework#30]
Hello, I'm trying to install the tool but I can't because there is no requirements.txt file. Help please. Thank you ! 
I found it complicate to find a updated article that explains how to install it. Why don't you create a Steps for Installment in your repo lol ? 

$ `sudo git clone https://github.com/graniet/operative-framework.git`
$ `cd operative-framework`
$ `sudo pip install -r requirements.txt`

![image](https://user-images.githubusercontent.com/61861342/76155846-00b3eb80-60c0-11ea-8db0-f987e9436337.png)

**Comment by zoben10** [comment]
I download the link you give, but now what's next ? 
Writing all the steps for installment will be useful for EVERYONE who will see this issue

![image](https://user-images.githubusercontent.com/61861342/76156083-1a0a6700-60c3-11ea-8e8b-7975a2b2c1a7.png)

**Comment by graniet** [comment]
Hello @zoben10,

Thanks for using operative framework,

i will make a documentation online soon.

**Comment by zoben10** [comment]
Thank you. But can you help please. What's next after I download the file

**Comment by tdelozie** [comment]
This is a known issue.  I asked about it a few months ago. Just be patient and check back in from time to time.

**Comment by graniet** [comment]
it's a priority for me now, i will make this for this sunday at end of the day. i come back here when it's done.

**Comment by graniet** [comment]
Hello @zoben10 @puddlejumper90 

You can see documentation here now: http://docs.operative-framework.com/

**Comment by zoben10** [comment]
Excellent travail @graniet Merci beaucoup !

**Comment by zoben10** [comment]
La commande: "target type" ne fonctionne pas. Comment dois-je faire pour énumérer la liste de "type" ? Merci @graniet

**Comment by puddlejumper90** [comment]
Thanks for update @graniet , I didn't realize you had a website dedicated to this application. Much appreciated!

**Comment by Mo18flash** [comment]
Same error for me :( 
And the link don't work

**Comment by puddlejumper90** [comment]
> Same error for me :( And the link don't work

I see it too, that's weird. Is this repo still active, @graniet?
