### ISSUE TITLE
'target type' command 

### ISSUE THREAD

**Issue by Rukasu4qr4** [graniet/operative-framework#31]
I don't know if this issue was present in previous versions, but in the newest voyager v1.10 this command isn't working although being mentioned in documentation. 
However 'target add list type' is working instead. 
![opfv](https://user-images.githubusercontent.com/62392943/78884736-b70e4600-7a5b-11ea-85a5-0f3a9f0c2894.png)

**Comment by graniet** [comment]
Hello,

Thanks for using operative framework,

Yes this is a mistake, target type command as not found for now.

Thanks you for this report, i will make this soon for the next build.
