### ISSUE TITLE
target type command display nothing

### ISSUE THREAD

**Issue by daynok** [graniet/operative-framework#32]
Not sure if this is the best place to report bugs in documentation or not

-- from http://docs.operative-framework.com/#/pages/fr/target

Issue: target type returns nothing
[OPF v1.10 (voyager)]: target type
[OPF v1.10 (voyager)]:

-- Attempt to add an incorrect target type will display list of target types
[OPF v1.10 (voyager)]: target add foo foo
+------------+
| TYPE       |
+------------+
| username   |
| ip_address |
| command    |
| text       |
| website    |
| url        |
| search     |
|            |
| instagram  |
| file       |
| enterprise |
| mac        |
| email      |
| phone      |
| country    |
| twitter    |
| session    |
| person     |
| software   |
| whatsapp   |
+------------+
[2020-04-09 13:20:11] : Please configure valid type
[2020-04-09 13:20:11] : this 'foo' type isn't available

**Comment by graniet** [comment]
Hello,

Thanks for using operative framework,

Yes this is a mistake, **target type** command as not found for now.

Thanks you for this report, i will make this soon for the next build.
