### ISSUE TITLE
How its start / launch ... ?

### ISSUE THREAD

**Issue by lillois59** [graniet/operative-framework#43]
Hi, 

I followed the installation instructions and everything looks correct except after the order:
  go build (ok) but after that nothing happens when I do the following command
./operative-framework

how to fix this

OSX high sierra
go version go1.16.6 darwin/amd64

merci

**Comment by anoduck** [comment]
Iff all that you see is an indented cursor, in my case blinking, you are good to go and have made it to the CLI. Type `help` and it should give you output of commands. 

I say this, because for some reason or another the CLI prompt is not being printed in the newest release.

**Comment by graniet** [comment]
Hello,

A Rust version is available in beta on the v2-rustlang branch, and it will be merged into the master branch.

The Go version is outdate

**Comment by anoduck** [comment]
Happy dance! I am so excited.

**Comment by anoduck** [comment]
@graniet Built in `OpenBSD Current Snapshot ~7.3` without a hitch. Pumping away just fine. Good job!
