### ISSUE TITLE
Multiple issues with binary package AND build dependencies appear to no longer be maintained.

### ISSUE THREAD

**Issue by anoduck** [graniet/operative-framework#45]
* Download and initial execution of framework functions, but no prompt is displayed once within the shell framework. The only thing visible is an indented cursor. i.e ` ----> |  `. This makes navigation difficult.
* During attempt to use the `account.checker` module, received error `can't load website listing.`. Could not readily discover exactly how to remedy this. 
* During use with `phone.*` modules encountered difficulty with providing PATH for vcard.
* Went to attempt to build binary to hopefully resolve encountered issues. Url for glide dependency "cli' has changed for manifest.
* Glide's website is no longer active, thus the installation script for glide is not accessible. Project appears to not have been touched in over three years.

**Comment by graniet** [comment]
Hello,

Thank for this report.

I work on new version of operative framework written in rustlang, i will push it very soon.

I think this version, solve many error.

**Comment by anoduck** [comment]
@graniet Oh nice, exciting news! I have used it nearly a year ago without any issues before, and I really liked the CLI interface and structure.  Very robust framework. I look forward to the next release. 

Looks like I need to begin learning rust myself, it is exploding in popularity.
