### ISSUE TITLE
Operative gives "can't find" errors on every module

### ISSUE THREAD

**Issue by ProjetsFromB** [graniet/operative-framework#46]
[OPF v1.20 (perception)] (0): linkedin.search set TARGET google
[OPF v1.20 (perception)] (0): linkedin.search list
+----------------+-----------------------------------+------------+----------+---------+
| ARGUMENT       | DESCRIPTION                       | VALUE      | REQUIRED | TYPE    |
+----------------+-----------------------------------+------------+----------+---------+
| TARGET         | Enterprise Name                   | google     | YES      | STRING  |
| LIMIT          | Limit search                      | 10         | NO       | STRING  |
| FILTER         | Use module filter after execution | NO DEFAULT | NO       | STRING  |
| BACKGROUND     | Run this task in background       | false      | NO       | BOOLEAN |
| DISABLE_OUTPUT | Display module result in stdout   | false      | NO       | BOOLEAN |
+----------------+-----------------------------------+------------+----------+---------+
[OPF v1.20 (perception)] (0): linkedin.search run
[2023-01-15 10:50:41] : can't find selected target
[2023-01-15 10:50:41] : error with a push to webserver: can't find selected target
[OPF v1.20 (perception)] (0):

**Comment by graniet** [comment]
Hello,

A Rust version is available in beta on the v2-rustlang branch, and it will be merged into the master branch.

The Go version is outdated.
