### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by talal2** [graniet/operative-framework#7]
Hi !
There's an error in 'core/modules/viadeo_search' => 'core/modules/video_search'

BTW: Nice script, good luck ;) :)

**Comment by graniet** [comment]
Hello, 

thanks for you issue, but is correct this module use Viadeo (http://fr.viadeo.com/en/).

like linkedin but in France.

**Comment by talal2** [comment]
Ooops,

If you're french, bonne continuation, et bonne chançe Mr .

                       Cordialement ...



2017-07-22 21:45 GMT+01:00 Graniet 75 <notifications@github.com>:

**Comment by graniet** [comment]
Merci à vous.
